# Build settings 
include: ["_pages"]

# General Translations
language: 
  en: En 
  fr: Fr
Contact:
  en: Contact Us
  fr: Nous-joindre
Pricing:
  en: Pricing
  fr: Tarification
FreeTrial:
  en: Free Trial
  fr: Essai gratuit
ChannelList:
  en: Channel List
  fr: Listes des chaines
Tutorials:
  en: Tutorials
  fr: Tutoriels
Home:
  en: Home
  fr: Acceuil
Email:
  en: Email
  fr: Courriel
Address:
  en: Address
  fr: Adresse
Phone:
  en: Phone
  fr: Téléphone
MandatoryField:
  en: Mandatory
  fr: Obligatoire
