# Build settings 
include: ["_pages"]

# General Translations
language: 
  en: En 
  fr: Fr
Contact:
  en: Contact Us
  fr: Nous-joindre
Purchases:
  en: Purchases
  fr: Achats
Tutorials:
  en: Tutorials
  fr: Tutoriels
Home:
  en: Home
  fr: Acceuil
Email:
  en: Email
  fr: Courriel
Address:
  en: Address
  fr: Adresse
Phone:
  en: Phone
  fr: Téléphone
MandatoryField:
  en: Mandatory
  fr: Obligatoire
